language: ruby
rvm:
  - "2.2.2"

sudo: true
cache: bundler

before_script: |
  cp config/database.example.yml config/database.yml
  cp config/lab_manager.example.yml config/lab_manager.yml

script: bundle exec rspec
