language: ruby
rvm:
  - "2.2.2"

sudo: false
cache: bundler

addons:
  postgresql: 9.3

services:
  - redis

before_script: |
  cp config/database.yml.example config/database.yml
  cp config/vsphere.yml.example config/vsphere.yml
  cp config/lab_manager.yml.example config/lab_manager.yml
  cp config/static_machine.yml.example config/static_machine.yml
  rake db:drop db:create db:migrate

script: bundle exec rspec
